### ISSUE TITLE
Sometimes list of orders is not loaded in popup

### ISSUE THREAD

**Issue by sidoruk-sv** [wix-playground/wix-meido-improver#6]
Please add a button to be able to trigger fetching all orders manually.

![Meido+2019-07-22+17-36-09](https://user-images.githubusercontent.com/439289/61641170-5362a380-aca7-11e9-926c-b1a687bf40dd.png)

**Comment by sidoruk-sv** [comment]
As inspected in the background script, only such requests are triggered:
* `/both-ratings`
* `/favorites`

**Comment by ghost** [comment]
Hey!
Thanks for your contribution! <3
 
The bug already fixed in version 1.8.0. (Meido changed HTML markdown)
Loading orders from the popup is not possible cause it doesn't have auth cookie token;
I have added `clear cache` button in the options page to have the ability to erase all data and load it again;
